import { zodResolver } from '@hookform/resolvers/zod'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useCallback } from 'react'
import { useForm } from 'react-hook-form'

import Button from '@/components/atoms/Button'
import InputField from '@/components/atoms/InputField'
import { trpc } from '@common/trpc'
import { ISignUp, signUpSchema } from '@common/validation/auth'

const SignUp: NextPage = () => {
  const router = useRouter()

  const { handleSubmit, register, reset } = useForm<ISignUp>({
    defaultValues: {
      cpf: '',
      password: '',
    },
    resolver: zodResolver(signUpSchema),
  })

  const { mutateAsync } = trpc.signup.useMutation()

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      console.log(data)
      try {
        const result = await mutateAsync(data)
        if (result.status === 201) {
          reset()
          router.push('/')
        }
      } catch (err) {
        console.error(err)
      }
    },
    [mutateAsync, router, reset]
  )

  return (
    <div>
      <Head>
        <title>Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-screen w-full">
        <form
          className="bg-gray-100 rounded px-8 pt-6 pb-8 mb-4"
          onSubmit={handleSubmit(onSubmit)}
        >
          <InputField
            id="cpf"
            label="CPF"
            type="text"
            placeholder="Digite seu CPF"
            required={true}
            register={register}
          />
          <InputField
            id="password"
            label="Senha"
            type="password"
            placeholder="Digite sua senha"
            required={true}
            register={register}
          />

          <div className="card-actions items-center justify-between">
            <Button color="secondary" type="submit">
              Sign Up
            </Button>
            <Button color="secondary">
              <Link href="/" className="link">
                SignIn
              </Link>
            </Button>
          </div>
        </form>
      </main>
    </div>
  )
}

export default SignUp
